### ISSUE TITLE
The sqlite is disabled by if 0

### ISSUE THREAD

**Issue by kopinions** [Minres/SystemC-Components#19]
https://github.com/Minres/SystemC-Components/blob/21e139480f969848d9954879350687a09ae44ad3/src/sysc/scc/tracer.cpp#L66
Any reason about disable the sqlite?

**Comment by eyck** [comment]
Actually this was a quick fix for portability.

In the past the SQLite backend turned out to be very slow due to the SQL guarantees of [ACID](https://de.wikipedia.org/wiki/ACID) transactions. Therefore it has not been used at all which motivated the change. But it can easily be converted into a compile time option.

**Comment by eyck** [comment]
@staskau Could you please modify the cmake configuration accordingly?
