### ISSUE TITLE
Possible memory leak created by using find_or_create

### ISSUE THREAD

**Issue by mslijepc** [Minres/SystemC-Components#32]
Hi, 

I have run `asan` (but not on the original repo) and found possible memory leak in: 
https://github.com/Minres/SystemC-Components/blob/ad8aef0430a196df822740fa9984885553ce45f1/src/bus_interfaces/axi/pin/axi4_target.h#L250

`fsm_handle` object is created by calling `find_or_create`, but never deleted

**Comment by mslijepc** [comment]
Or the memory management is the responsibility of `find_or_create` ?

**Comment by eyck** [comment]
Indeed this is a memory leak. The fsm handles are created https://github.com/Arteris-IP/tlm2-interfaces/blob/48e2de7033275bfc1807925e96154d43325a7325/axi/fsm/base.cpp#L53. Once the bus transaction is finished they are returned into a pool o fhandles (https://github.com/Arteris-IP/tlm2-interfaces/blob/48e2de7033275bfc1807925e96154d43325a7325/axi/fsm/base.h#L165). But this pool is not freed upon destruction thus in principle creating a memory leak. Since there is no dynamic instantiation of modules (and hence axi fsms) we did not see this critical yet.
